services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    tmpfs:
      - /tmp

  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_API_KEY: ${NEXT_PUBLIC_API_KEY}
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api
      - postgres

  postgres:
    image: pgvector/pgvector:pg16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
